[package]
name = "todos"
version = "0.1.0"
authors = ["Pepe Becker <mail@pepebecker.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
serde = "1.0.80"
serde_json = "1.0"
serde_derive = "1.0.80"
